module.exports = {
  "1.msc": "Single B2 cell with 1px solid black on all sides",
  "2.msc": "Single B2 cell with 2px solid black on all sides",
  "3.msc": "Single B2 cell with 1px dotted black",
  "4.msc": "Single B2 cell with 1px dashed black",
  "5.msc": "Single B2 cell with 2px solid red",
  "6.msc": "Single B2 cell with 3px double black",
  "7.msc": "Single B2 cell with 3px solid green",
  "8.msc": "Single B2 cell with 1px solid blue",
  "9.msc": "Single B2 cell with 1px solid gray",
  "10.msc": "Single B2 cell with 4px solid heavy black",
  "11.msc": "Single B2 cell with top border only",
  "12.msc": "Single B2 cell with right border only",
  "13.msc": "Single B2 cell with bottom border only",
  "14.msc": "Single B2 cell with left border only",
  "15.msc": "Single B2 cell with top and bottom borders",
  "16.msc": "Column B width 30px",
  "17.msc": "Column B width 80px",
  "18.msc": "Columns B and C widths 40px and 90px",
  "19.msc": "Columns B-D widths 25/50/75",
  "20.msc": "Five equal columns 60px",
  "21.msc": "Alternating widths 20/70/20/70",
  "22.msc": "Narrow gutter on A (8px) and wide B (120px)",
  "23.msc": "Square grid columns 50px across B-E",
  "24.msc": "Wide first data col 140px then 60px",
  "25.msc": "Tiny spacer column C 5px with wider neighbors",
  "26.msc": "Merge example: Horizontal merge across B-C",
  "27.msc": "Merge example: Horizontal merge across B-D",
  "28.msc": "Merge example: Vertical merge down B2:B3",
  "29.msc": "Merge example: Vertical merge down B2:B4",
  "30.msc": "Merge example: 2x2 block merge starting B2",
  "31.msc": "Merge example: 3x2 block merge starting B2",
  "32.msc": "Merge example: 2x3 block merge starting B2",
  "33.msc": "Merge example: Cross shape with vertical B3:B5 and horizontal C4:D4",
  "34.msc": "Merge example: Header row merge B2:E2 with body cells below",
  "35.msc": "Merge example: Side label merge down B2:B5 with row cells C2:E5",
  "36.msc": "Single cell with 5px padding middle align",
  "37.msc": "Single cell with 10px padding middle align",
  "38.msc": "Single cell with 15px padding top align",
  "39.msc": "Single cell with 10px top/bottom padding only",
  "40.msc": "Single cell with 12px left/right padding only",
  "41.msc": "Single cell with 6px padding bottom align",
  "42.msc": "Single cell with 20px padding center align",
  "43.msc": "Single cell with Stacked padding: left 8px vs right 16px",
  "44.msc": "Single cell with Compact padding 3px with top align",
  "45.msc": "Single cell with Wide padding 24px bottom align",
  "46.msc": "Single cell with light gray background",
  "47.msc": "Single cell with soft yellow background",
  "48.msc": "Single cell with pale blue background",
  "49.msc": "Single cell with mint background",
  "50.msc": "Single cell with peach background",
  "51.msc": "Single cell with lavender background",
  "52.msc": "Single cell with light cyan background",
  "53.msc": "Single cell with light pink background",
  "54.msc": "Single cell with sand background",
  "55.msc": "Single cell with ghost white background",
  "56.msc": "Centered label 'Center'",
  "57.msc": "Left aligned label 'Left'",
  "58.msc": "Right aligned label 'Right'",
  "59.msc": "Top aligned text with 8pt",
  "60.msc": "Bottom aligned text with 12pt",
  "61.msc": "Bold header in 14pt",
  "62.msc": "Italic note in 10pt",
  "63.msc": "Mono text 11pt",
  "64.msc": "Wide title with padding",
  "65.msc": "Label with right align and 6px padding",
  "66.msc": "2x2 grid with all borders",
  "67.msc": "3x3 grid with all borders",
  "68.msc": "4x4 checker black/white",
  "69.msc": "3x4 vertical stripes gray/white",
  "70.msc": "5x2 header band top row shaded",
  "71.msc": "2x3 with alternating pastel rows",
  "72.msc": "3x3 with thick outer border",
  "73.msc": "2x4 with only column borders",
  "74.msc": "Row stripe table 4x3 light blue bands",
  "75.msc": "Column stripe table 4x3 warm grays",
  "76.msc": "3x3 with center cell highlighted",
  "77.msc": "2x2 with diagonally different colors",
  "78.msc": "3x2 grid with first column bold border",
  "79.msc": "4x2 grid with bottom row shaded",
  "80.msc": "2x5 tall list with alternating shading",
  "81.msc": "Merged header over 3 cols with border and padding",
  "82.msc": "Left sidebar merged rows with shaded background",
  "83.msc": "Two-column layout with different padding",
  "84.msc": "Top border only row of 3 cells",
  "85.msc": "Bottom border only row of 3 cells",
  "86.msc": "Alternating column backgrounds with no borders",
  "87.msc": "Outline table with header shade",
  "88.msc": "Four-cell block with different border weights, swastik symbol",
  "89.msc": "Two-row layout with top padding heavier",
  "90.msc": "Thick outline with inner thin grid",
  "91.msc": "Three columns with alternating padding and background",
  "92.msc": "Two-column comparison with different font weights",
  "93.msc": "Row of three with only outer borders",
  "94.msc": "Card with title and body padding",
  "95.msc": "Dashboard: merged header, two columns, shaded sidebar",
  "96.msc": "Invoice header: merged title and two detail rows",
  "97.msc": "Comparison grid with alternating borders",
  "98.msc": "Checklist layout with left ticks column narrow",
  "99.msc": "Kanban lanes three columns with colored headers",
  "100.msc": "Blank canvas with outer border and gutters"
}
